HotelFlight/HotelFlight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('', include('login.urls')),
]

HotelFlight/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('reg/', views.reg, name='reg')
]

HotelFlight/search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('ok/', views.test, name='homepage'),
    path('searchHotel', views.searchHotelPage, name='searchHotelPage')
]

HotelFlight/database/models.py
import re
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    Phone = models.PositiveIntegerField()
    Address = models.CharField(max_length=1000)
    Passport_Number = models.CharField(max_length=100, null=True)
    Payment_Info = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.user.username


class Hotel(models.Model):
    Hotel_Name = models.CharField(max_length=200)
    Hotel_Location = models.CharField(max_length=500)
    Hotel_Country = models.CharField(max_length=500, null=True)
    TotalSentMoney = models.DecimalField(max_digits=20, decimal_places=2)
    Percentage = models.DecimalField(max_digits=3, decimal_places=2)
    CompanyAdmin = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    Description = models.TextField(null=True)

    def __str__(self):
        return self.Hotel_Name


class Room(models.Model):
    SingleBedCount = models.DecimalField(max_digits=1, decimal_places=0)
    DoubleBedCount = models.DecimalField(max_digits=1, decimal_places=0)
    RoomType = models.CharField(max_length=100)
    AirConditioner = models.BooleanField()

    def __str__(self):
        return self.RoomType


class Hotel_Room(models.Model):
    Hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    Room = models.ForeignKey(Room, on_delete=models.CASCADE)
    Price = models.DecimalField(max_digits=20, decimal_places=2)
    Complimentary_Breakfast = models.BooleanField()
    Wifi = models.BooleanField()
    Checkin_Date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    Checkout_Date = models.DateField(auto_now=False, auto_now_add=False, null=True)

HotelFlight/search/models.py
from django.db import models

# Create your models here.

HotelFlight/login/forms.py
from django import forms
from database.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=20)
    last_name = forms.CharField(required=True, max_length=20)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('Phone', 'Address')

HotelFlight/search/forms.py
from django import forms
import datetime

CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)


class SearchHotelForm(forms.Form):
    hoteldest = forms.CharField(label='Hotel or destination place', max_length=100)
    checkin = forms.DateField()
    checkout = forms.DateField()
    room = forms.CharField(widget=forms.Select(choices=CHOICES))
    adult = forms.CharField(widget=forms.Select(choices=CHOICES))
    children = forms.CharField(widget=forms.Select(choices=CHOICES))
    # checkout = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    # room = forms.IntegerField(label='Room', widget=forms.NumberInput(
    #    attrs={'type': 'range', 'step': '1', 'min': '1', 'max': '10', 'value': '1'}))
    #   children = forms.IntegerField(label='Children', widget=forms.NumberInput(
    #    attrs={'type': 'range', 'step': '1', 'min': '1', 'max': '10', 'value': '0'}))

HotelFlight/database/views.py
from django.shortcuts import render

# Create your views here.

HotelFlight/login/views.py
from django.shortcuts import render
from .forms import ProfileForm, UserCreateForm
from django.http import HttpResponseRedirect
from django.contrib import auth,messages


# Create your views here.


def login(request):
    redirect_to = request.GET.get('next', '')
    print('kkk  '+redirect_to)
    if request.method == 'POST':
        Username = request.POST.get("username", "")
        Password = request.POST.get("pass", "")
        print(Username)
        print(Password)
        user = auth.authenticate(request, username=Username, password=Password)
        if user is not None:
            print("Correct!")
            auth.login(request, user)
            return HttpResponseRedirect(redirect_to)
        else:
            print("Invalid password.")
            messages.error(request, 'Username or password not correct')
    return render(request, "login/login.html")


def reg(request):
    submitted = False
    if request.method == 'POST':
        userform = UserCreateForm(request.POST)
        profileform = ProfileForm(request.POST)
        if userform.is_valid() and profileform.is_valid():
            user = userform.save()
            profile = profileform.save(commit=False)
            profile.user = user
            profile.save()
            print('Account created successfully')
        else:
            print('ERRRR')
            print(userform.errors)
    else:
        userform = UserCreateForm()
        profileform = ProfileForm()
    return render(request, "login/reg.html", {'userform': userform, 'profileform': profileform, 'submitted': submitted})

HotelFlight/search/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import SearchHotelForm
from django.db import connection
from django.core.paginator import Paginator
from collections import namedtuple


# Create your views here.


def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


def homepage(request):
    form = SearchHotelForm()
    return render(request, "search/homepage.html", {'form': form})


def searchHotelPage(request):
    form = SearchHotelForm()
    dest = request.GET.get('hoteldest', '')
    checkin = request.GET.get('checkin', '')
    checkout = request.GET.get('checkout', '')
    roomcount = request.GET.get('room', '')
    adultcount = request.GET.get('adult', '')
    print(checkin)
    dest = '%' + dest + '%'
    roomcount = int(roomcount)
    cursor = connection.cursor()
    cursor.execute("SELECT H.Hotel_Name,H.Hotel_Location,H.Hotel_Country,H.Description,count(*) as 'Num',"
                   "min(HR.Price)*%s as 'Price', H.CompanyAdmin_id as ID  FROM database_hotel_room HR "
                   "join database_hotel H on(HR.Hotel_id=H.id)"
                   "where ((lower(H.Hotel_Name) Like %s OR lower(H.Hotel_Location) Like %s OR "
                   "lower(H.Hotel_Country) Like %s) and HR.Checkout_Date <= %s)"
                   "GROUP BY H.Hotel_Name HAVING Num >= %s", [roomcount, dest, dest, dest, checkin, roomcount])
    data = namedtuplefetchall(cursor)
    paginator = Paginator(data, 5)
    page = request.GET.get('page')
    hotels = paginator.get_page(page)
    return render(request, "search/searchHotel.html", {'form': form, 'hotels': hotels})


# @login_required(login_url='/login/')
def test(request):
    return render(request, "search/test.html")

HotelFlight/HotelFlight/templates/login/login.html
{% extends "login/base.html" %}

{% load staticfiles %}


{% block title %}Login{% endblock title %}


{% block content %}

<div class="limiter">
    <div class="container-login100" style="background-image: url({% static 'login/images/bg-01.jpg' %});">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-90 p-b-54">
            <form action="" class="login100-form validate-form" method="POST">
					<span class="login100-form-title p-b-40">
						Login
					</span>
                {% for message in messages %}
                <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>

                    {{ message }}

                </div>
                {% endfor %}
                <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                    <span class="label-input100">Username</span>
                    <input class="input100" type="text" name="username" placeholder="Type your username">
                    <span class="focus-input100" data-symbol="&#xf206;"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <span class="label-input100">Password</span>
                    <input class="input100" type="password" name="pass" placeholder="Type your password">
                    <span class="focus-input100" data-symbol="&#xf190;"></span>
                </div>

                <div class="text-right p-t-8 p-b-31">
                    <a href="#">
                        Forgot password?
                    </a>
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                </div>

                <div class="txt1 text-center p-t-54 p-b-20">
						<span>
							Or Sign Up Using
						</span>
                </div>

                <div class="flex-c-m">
                    <a href="#" class="login100-social-item bg1">
                        <i class="fa fa-facebook"></i>
                    </a>

                    <a href="#" class="login100-social-item bg2">
                        <i class="fa fa-twitter"></i>
                    </a>

                    <a href="#" class="login100-social-item bg3">
                        <i class="fa fa-google"></i>
                    </a>
                </div>

                <div class="flex-col-c p-t-155">
						<span class="txt1 p-b-17">
							Or Sign Up Using
						</span>

                    <a href="#" class="txt2">
                        Sign Up
                    </a>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>


{% endblock content %}

HotelFlight/HotelFlight/templates/login/reg.html
{% load static %}
{% load widget_tweaks %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'login/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'login/css/mycss.css' %}">
</head>
<body>

<div class="main">

    <section class="signup">
        <!-- <img src="images/signup-bg.jpg" alt=""> -->
        <div class="container">
            <div class="signup-content">
                <form method="POST" id="signup-form" class="signup-form">
                    {{ form.non_field_errors }}
                    {{ form.errors }}
                    <h2 class="form-title">Create account</h2>
                    {% for field in userform %}
                    <div class="form-group">
                        {% if field.errors %}
                        <div class="isa_error">
                            {% if field.errors %}
                            <ol>
                                {% for error in field.errors %}
                                <li>{{ error|escape }}</li>
                                {% endfor %}
                            </ol>
                            {% endif %}
                        </div>
                        {% endif %}
                        {% render_field field class="form-input" placeholder=field.label %}
                        <!-- <input type="text" class="form-input" name="name" id="name" placeholder="Your Name"/> -->
                    </div>
                    {% endfor %}


                    {% for field in profileform %}
                    <div class="form-group">
                        {{ field.errors }}
                        {% render_field field class="form-input" placeholder=field.label %}
                        <!-- <input type="text" class="form-input" name="name" id="name" placeholder="Your Name"/> -->
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <input type="checkbox" name="agree-term" id="agree-term" class="agree-term"/>
                        <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all
                            statements in <a href="#" class="term-service">Terms of service</a></label>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                    </div>
                    {% csrf_token %}
                </form>
                <p class="loginhere">
                    Have already an account ? <a href="{% url 'login' %}" class="loginhere-link">Login here</a>
                </p>
            </div>
        </div>
    </section>

</div>

<!-- JS -->
<script src="{% static 'login/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'login/js/main.js' %}"></script>
</body>
</html>

HotelFlight/HotelFlight/templates/search/homepage.html
{% extends "search/base.html" %}

{% load staticfiles %}

{% load widget_tweaks %}


{% block title %}Homepage{% endblock title %}


{% block content %}

<div class="home">

    <!-- Home Slider -->

    <div class="home_slider_container">

        <div class="owl-carousel owl-theme home_slider">

            <!-- Slider Item -->
            <div class="owl-item home_slider_item">
                <!-- Image by https://unsplash.com/@anikindimitry -->
                <div class="home_slider_background"
                     style="background-image: url({% static 'search/images/home_slider.jpg' %})"></div>

                <div class="home_slider_content text-center">
                    <div class="home_slider_content_inner" data-animation-in="flipInX"
                         data-animation-out="animate-out fadeOut">
                        <h1>discover</h1>
                        <h1>the world</h1>
                        <div class="button home_slider_button">
                            <div class="button_bcg"></div>
                            <a href="#">explore now<span></span><span></span><span></span></a></div>
                    </div>
                </div>
            </div>

            <!-- Slider Item -->
            <div class="owl-item home_slider_item">
                <div class="home_slider_background"
                     style="background-image:url({% static 'search/images/home_slider.jpg' %})"></div>

                <div class="home_slider_content text-center">
                    <div class="home_slider_content_inner" data-animation-in="flipInX"
                         data-animation-out="animate-out fadeOut">
                        <h1>discover</h1>
                        <h1>the world</h1>
                        <div class="button home_slider_button">
                            <div class="button_bcg"></div>
                            <a href="#">explore now<span></span><span></span><span></span></a></div>
                    </div>
                </div>
            </div>

            <!-- Slider Item -->
            <div class="owl-item home_slider_item">
                <div class="home_slider_background"
                     style="background-image:url({% static 'search/images/home_slider.jpg' %})"></div>

                <div class="home_slider_content text-center">
                    <div class="home_slider_content_inner" data-animation-in="flipInX"
                         data-animation-out="animate-out fadeOut">
                        <h1>discover</h1>
                        <h1>the world</h1>
                        <div class="button home_slider_button">
                            <div class="button_bcg"></div>
                            <a href="#">explore now<span></span><span></span><span></span></a></div>
                    </div>
                </div>
            </div>

        </div>

        <!-- Home Slider Nav - Prev -->
        <div class="home_slider_nav home_slider_prev">
            <svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="28px" height="33px" viewBox="0 0 28 33" enable-background="new 0 0 28 33" xml:space="preserve">
					<defs>
						<linearGradient id='home_grad_prev'>
							<stop offset='0%' stop-color='#fa9e1b'/>
                            <stop offset='100%' stop-color='#8d4fff'/>
						</linearGradient>
					</defs>
                <path class="nav_path" fill="#F3F6F9" d="M19,0H9C4.029,0,0,4.029,0,9v15c0,4.971,4.029,9,9,9h10c4.97,0,9-4.029,9-9V9C28,4.029,23.97,0,19,0z
					M26,23.091C26,27.459,22.545,31,18.285,31H9.714C5.454,31,2,27.459,2,23.091V9.909C2,5.541,5.454,2,9.714,2h8.571
					C22.545,2,26,5.541,26,9.909V23.091z"/>
                <polygon class="nav_arrow" fill="#F3F6F9" points="15.044,22.222 16.377,20.888 12.374,16.885 16.377,12.882 15.044,11.55 9.708,16.885 11.04,18.219
					11.042,18.219 "/>
				</svg>
        </div>

        <!-- Home Slider Nav - Next -->
        <div class="home_slider_nav home_slider_next">
            <svg version="1.1" id="Layer_3" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="28px" height="33px" viewBox="0 0 28 33" enable-background="new 0 0 28 33" xml:space="preserve">
					<defs>
						<linearGradient id='home_grad_next'>
							<stop offset='0%' stop-color='#fa9e1b'/>
                            <stop offset='100%' stop-color='#8d4fff'/>
						</linearGradient>
					</defs>
                <path class="nav_path" fill="#F3F6F9" d="M19,0H9C4.029,0,0,4.029,0,9v15c0,4.971,4.029,9,9,9h10c4.97,0,9-4.029,9-9V9C28,4.029,23.97,0,19,0z
				M26,23.091C26,27.459,22.545,31,18.285,31H9.714C5.454,31,2,27.459,2,23.091V9.909C2,5.541,5.454,2,9.714,2h8.571
				C22.545,2,26,5.541,26,9.909V23.091z"/>
                <polygon class="nav_arrow" fill="#F3F6F9" points="13.044,11.551 11.71,12.885 15.714,16.888 11.71,20.891 13.044,22.224 18.379,16.888 17.048,15.554
				17.046,15.554 "/>
				</svg>
        </div>

        <!-- Home Slider Dots -->

        <div class="home_slider_dots">
            <ul id="home_slider_custom_dots" class="home_slider_custom_dots">
                <li class="home_slider_custom_dot active">
                    <div></div>
                    01.
                </li>
                <li class="home_slider_custom_dot">
                    <div></div>
                    02.
                </li>
                <li class="home_slider_custom_dot">
                    <div></div>
                    03.
                </li>
            </ul>
        </div>

    </div>

</div>


<!-- Search -->

<div class="search">


    <!-- Search Contents -->

    <div class="container fill_height">
        <div class="row fill_height">
            <div class="col fill_height">

                <!-- Search Tabs -->

                <div class="search_tabs_container">
                    <div class="search_tabs d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-between justify-content-start">
                        <div class="search_tab active d-flex flex-row align-items-center justify-content-lg-center justify-content-start">
                            <img src="{% static 'search/images/suitcase.png' %}" alt=""><span>hotels</span></div>
                        <div class="search_tab d-flex flex-row align-items-center justify-content-lg-center justify-content-start">
                            <img src="{% static 'search/images/departure.png' %}" alt="">flights
                        </div>
                    </div>
                </div>

                <!-- Search Panel -->

                <div class="search_panel active">
                    <form action="{% url 'searchHotelPage' %}" id="search_form_1" method="get"
                          class="search_panel_content d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-between justify-content-start">

                        <div class="search_item">
                            <div>destination</div>
                            {% render_field form.hoteldest class="destination search_input" placeholder=form.hoteldest.label %}
                            <!-- <input type="text" class="destination search_input" required="required"> -->
                        </div>
                        <div class="search_item" style="margin-top: 12px">
                            <div>check in</div>
                            {% render_field form.checkin class="check_in search_input" placeholder=form.checkin.label %}
                            <!-- <input type="text" class="check_in search_input" placeholder="YYYY-MM-DD"> -->
                        </div>
                        <div class="search_item" style="margin-top: 12px">
                            <div>check out</div>
                            {% render_field form.checkout class="check_out search_input" placeholder=form.checkin.label %}
                            <!-- <input type="text" class="check_out search_input" placeholder="YYYY-MM-DD">-->
                        </div>
                        <div class="search_item">
                            <div>room</div>
                            {% render_field form.room class="search_input" placeholder=form.room.label %}
                        </div>
                        <div class="search_item">
                            <div>adults</div>
                            {% render_field form.adult class="search_input" placeholder=form.adult.label %}
                        </div>
                        <div class="search_item">
                            <div>children</div>
                            {% render_field form.children class="search_input" placeholder=form.children.label %}
                        </div>
                        <button class="button search_button">search<span></span><span></span><span></span></button>
                        {% csrf_token %}
                    </form>
                </div>

                <!-- Search Panel -->

                <div class="search_panel">
                    <form action="#" id="search_form_2"
                          class="search_panel_content d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-between justify-content-start">
                        <div class="search_item">
                            <div>destination</div>
                            <input type="text" class="destination search_input" required="required">
                        </div>
                        <div class="search_item">
                            <div>check in</div>
                            <input type="text" class="check_in search_input" placeholder="YYYY-MM-DD">
                        </div>
                        <div class="search_item">
                            <div>check out</div>
                            <input type="text" class="check_out search_input" placeholder="YYYY-MM-DD">
                        </div>
                        <div class="search_item">
                            <div>adults</div>
                            <select name="adults" id="adults_2" class="dropdown_item_select search_input">
                                <option>01</option>
                                <option>02</option>
                                <option>03</option>
                            </select>
                        </div>
                        <div class="search_item">
                            <div>children</div>
                            <select name="children" id="children_2" class="dropdown_item_select search_input">
                                <option>0</option>
                                <option>02</option>
                                <option>03</option>
                            </select>
                        </div>
                        <button class="button search_button">search<span></span><span></span><span></span></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block jscript %}
<script>
    var today = new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + new Date().getDate()
    var tommorrow = new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + (new Date().getDate()+1)
    $('#id_checkin').datepicker({
        uiLibrary: 'bootstrap4',
        value: today,
        minDate: today,
        format: 'yyyy-mm-dd',
        size: 'small'
    });
    $('#id_checkout').datepicker({
        uiLibrary: 'bootstrap4',
        value: tommorrow,
        minDate: tommorrow,
        format: 'yyyy-mm-dd',
        size: 'small'
    });
</script>
{% endblock jscript %}